language: node_js
dist: trusty
sudo: required

jobs:
  include:
    # Test that it builds correctly
    ###############################
    - stage: build test
      if: tag !~ ^release*$"
      services:
        - docker
      script:
        - docker-compose -f "$(find . -maxdepth 1 -name "docker-compose*")" build

    # Deploy stage
    # - code below is common between DAppNode packages
    ##################################################
    - stage: release
      services:
        - docker
      script: skip
      node_js: lts/*
      before_deploy:
        - wget https://raw.githubusercontent.com/dappnode/DAppNode/dac9b3a964aaac93bf704344be0531b2e819d0e1/scripts/before_deploy.sh
        - source before_deploy.sh
        - dappnodesdk publish patch -p infura
      deploy:
        provider: releases
        prerelease: true
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        # $RELEASE_VERSION is exported on before_deploy.sh
        file: build_${RELEASE_VERSION}/*
        skip_cleanup: true
        # $TRAVIS_TAG is exported on before_deploy.sh
        name: "$TRAVIS_TAG"
        body: "# Changelog"
        on:
          branch: master
          tags: true
          condition: "$TRAVIS_TAG =~ ^release*$"
      after_deploy:
        - wget https://raw.githubusercontent.com/dappnode/DAppNode/master/scripts/after_deploy.sh
        - source after_deploy.sh
