version: '3.4'

networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.33.0.0/16

volumes:
  ethchaindnpdappnodeeth_data: {}
  
services:
  ethchain.dnp.dappnode.eth:
    build: ./build
    image: ethchain.dnp.dappnode.eth:0.1.4
    container_name: DAppNodeCore-ethchain.dnp.dappnode.eth
    restart: always
    volumes:
      - ethchaindnpdappnodeeth_data:/root/.local/share/io.parity.ethereum/
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    dns: 172.33.1.2
    networks:
      network:
        ipv4_address: 172.33.1.6